title:            Alison Rowland's Blog
tagline:          civic hacking and biggish data
description:      A blog about open-source software development in Python, Ruby, SQL, PostgreSQL, Javascript.
#Comment out url when working locally to resolve base urls correctly
#url:              http://your-site.com

# Owner/author information
owner:
  name:           Alison Rowland
  avatar:         bio-photo__small.png
  bio:            civic hacking and biggish data
  email:          alisonrowland@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        arowla 
  facebook:       
  github:         arowla
  linkedin:       
  instagram:      
  rdio:
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   https://plus.google.com/116141593322614137236

# Analytics and webmaster tools stuff goes here
google_analytics:  UA-44670130-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Articles
    url: /articles


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "vendor"]
